### ISSUE TITLE
Execption if there are no rows

### ISSUE THREAD

**Issue by jzakrzewski** [tecfu/tty-table#36]
# Problem Summary
If I render a table that has no rows I become an exception. 
## Expected Result (screen shot if possible)
This is ideal  (note the reduced row size):
```
  ┌─────────┬───────┬─────────┐
  │ Setting │ Value │ Default │
  ├─────────┼───────┼─────────┤
  └─────────┴───────┴─────────┘
```

## Actual Result (screen shot if possible)
```
    let z = new Array(iterable[0].length); //create a new empty row
                                  ^

TypeError: Cannot read property 'length' of undefined
    at Object.Format.inferColumnWidth (/somewhere/node_modules/tty-table/src/format.js:196:35)
    at /somewhere/node_modules/tty-table/src/format.js:237:25
    at Array.map (<anonymous>)
    at Object.Format.getColumnWidths (/somewhere/node_modules/tty-table/src/format.js:222:25)
    at Object.Render.stringifyData (/somewhere/node_modules/tty-table/src/render.js:36:79)
    at Array.Factory.tableObject.render (/somewhere/node_modules/tty-table/src/factory.js:196:25)
```

## Environment Information 

 * OS: any

 * Terminal Emulator: any

## Steps to Reproduce 
```js
const header = [
            {value: 'Setting', align: 'left'},
            {value: 'Value'},
            {value: 'Default'},
        ];
const rows = [];
return Table(header, rows, {compact: false}).render();
```
In reality the rows are generated from an external source and just evaluate to an empty array.

**Comment by tecfu** [comment]
Fixed by https://github.com/tecfu/tty-table/commit/0357c2585782eebdcecb1171d913040e869335d6.
