### ISSUE TITLE
Version 2.8.12 breaks backwards compatibility with version 2.8.11

### ISSUE THREAD

**Issue by ezzatron** [tecfu/tty-table#57]
# Problem Summary

Upgrading from `2.8.11` to `2.8.12` broke my application. After investigating, I noticed that [chalk was replaced with kleur in version 2.8.12](https://github.com/tecfu/tty-table/compare/v2.8.11...v2.8.12#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L52). I was using `whiteBright` as a header color, which is supported by chalk, but not kleur. This is a backwards compatibility break, and I think it should have caused in a major version bump.

In addition to the BC break, it's no longer possible to use bright/bold colors in headers as far as I can tell. I think you'd need to introduce a header equivalent to the `formatter` option to restore that functionality.

## Expected Result (screen shot if possible)

Using `whiteBright` as a header color should continue to work when upgrading from `2.8.11` to `2.8.12`.

## Actual Result (screen shot if possible)

Using `whiteBright` as a header color throws the following error:

```
TypeError: kleur[color] is not a function
    at /path/to/project/node_modules/tty-table/src/style.js:6:24
    at Array.reduce (<anonymous>:null:null)
    at Object.module.exports.color (/path/to/project/node_modules/tty-table/src/style.js:5:17)
    at Object.module.exports.colorizeCell (/path/to/project/node_modules/tty-table/src/style.js:28:19)
    at Object.module.exports.buildCell (/path/to/project/node_modules/tty-table/src/render.js:275:21)
    at Object.module.exports.buildRow (/path/to/project/node_modules/tty-table/src/render.js:177:21)
    at /path/to/project/node_modules/tty-table/src/render.js:45:24
    at Array.map (<anonymous>:null:null)
    at Object.module.exports.stringifyData (/path/to/project/node_modules/tty-table/src/render.js:44:45)
    at Array.Factory.tableObject.render (/path/to/project/node_modules/tty-table/src/factory.js:175:25)
    at outputSites (/path/to/project/node_modules/@codeworx/sparse-dev/src/server.js:112:34)
    at run (/path/to/project/node_modules/@codeworx/sparse-dev/src/server.js:69:15)
    at runMicrotasks (<anonymous>:null:null)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Environment Information 

 * OS: N/A
 * Terminal Emulator: N/A

## Steps to Reproduce 

Run this code using `2.8.11`, then `2.8.12`. Observe that the upgrade breaks BC:

```js
const Table = require('tty-table')

const header = [
  {
    value: 'Heading',
    headerColor: 'whiteBright',
  },
]
const rows = [['Row']]
const table = new Table(header, rows)

console.log(table.render())
```

**Comment by ezzatron** [comment]
@koden-km FYI

**Comment by tecfu** [comment]
Thanks for reporting. I will try to put out a fix within the next couple hours.

**Comment by tecfu** [comment]
[Fixed](https://github.com/tecfu/tty-table/commit/d916298a27fcfa38405fe6ae08f61bc78121f651). Please upgrade to v2.8.13 for now to restore [chalk](https://github.com/chalk/chalk) based behaviors.

Thanks again, and sorry for the inconvenience. Should have bumped major version.

**Comment by ezzatron** [comment]
Thank you!

**Comment by tecfu** [comment]
@ezzatron Absolutely. Also see 7e9e316 / version 3.0.1, in which chalk has been restored.
