### ISSUE TITLE
RangeError: Invalid array length

### ISSUE THREAD

**Issue by nuhasha** [tecfu/tty-table#97]
# Problem Summary
```
node_modules/tty-table/src/format.js:172
            + Array(padBoth + 1 + padRemainder).join(" ")
              ^
RangeError: Invalid array length

  at /node_modules/tty-table/src/format.js:172:15
    at Array.map (<anonymous>)
    at module.exports.wrapCellText (/node_modules/tty-table/src/format.js:156:35)
    at module.exports.buildCell (/node_modules/tty-table/src/render.js:287:39)
    at /node_modules/tty-table/src/render.js:171:26
    at Array.map (<anonymous>)
    at module.exports.buildRow (/node_modules/tty-table/src/render.js:170:13)
    at /node_modules/tty-table/src/render.js:47:24
    at Array.map (<anonymous>)
    at module.exports.stringifyData (/node_modules/tty-table/src/render.js:46:45)

Node.js v18.17.1
```
## Environment Information 

 * OS:

 * Terminal Emulator:

 * Node Version:

## Steps to Reproduce 

 1. foo
 2. bar
 3. baz

**Comment by tecfu** [comment]
Hi @nuhasha. Could you please post the command you are using to invoke `tty-table` as well as the data you are passing to it?

**Comment by tecfu** [comment]
Closing due to lack of data. Please feel free to re-submit this if you come across an example that can be replicated. Thanks.
